server:
  port: 9100

spring:
  zipkin:
    service:
      name: elastic-service
    enabled: true
    base-url: http://localhost:9411
  elasticsearch:
    uris: http://localhost:9200

logging:
  level:
    org.springframework: DEBUG
    com.muhammet.graphql: INFO
    root: trace
  file:
    name: elastic-service.log
  logback:
    rollingpolicy:
      max-file-size: 20MB

