server:
  port: 7090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/DBauthmicroservice
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

myapplication:
  auth:
    ip: localhost
    port: 9090
  user:
    ip: localhost
    port: 9093
    feignurl: http://localhost:9093/v1/dev/userprofile

buuygulama:
  birdeger: "YML dan gelen bir parametre"