server:
  port: 80
spring:
  application:
    name: api-gateway-microservice
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
      default-filters:
        - RewritePath= /(?<segment>.*) , /v1/dev/$\{segment}
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: auth-service
          uri: http://localhost:9090
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: auth
                fallbackUri: forward:/fallbackauth
        - id: product-service
          uri: http://localhost:9091
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: product
                fallbackUri: forward:/fallbackproduct
        - id: sales-service
          uri: http://localhost:9092
          predicates:
            - Path=/sales/**
          filters:
            - name: CircuitBreaker
              args:
                name: sales
                fallbackUri: forward:/fallbacksales
        - id: user-service
          uri: http://localhost:9093
          predicates:
            - Path=/userprofile/**
          filters:
            - name: CircuitBreaker
              args:
                name: user
                fallbackUri: forward:/fallbackuser


