server:
  port: 80
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: api-gateway
  application:
    name: api-gateway-microservice
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      default-filters:
        - RewritePath= /(?<segment>.*) , /v1/dev/$\{segment}
      routes:
        - id: auth-service
          uri: http://localhost:9090
          predicates:
            - Path=/auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: auth
                fallbackUri: forward:/fallbackauth
        - id: product-service
          uri: http://localhost:9091
          predicates:
            - Path=/product/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: product
                fallbackUri: forward:/fallbackproduct
        - id: sales-service
          uri: http://localhost:9092
          predicates:
            - Path=/sales/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: sales
                fallbackUri: forward:/fallbacksales
        - id: user-service
          uri: http://localhost:9093
          predicates:
            - Path=/userprofile/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: user
                fallbackUri: forward:/fallbackuser


