# DİKKAT!!!!! Sistem Ortam Deişkenlerine işlenen bilgiler, IDE yeniden başlatılana kadar aktif olmaz.
server:
  port: ${AUTH_PORT}

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.26:5432/DBauthmicroservice
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

myapplication:
  auth:
    ip: 192.168.1.26
    port: 9090
  user:
    ip: 192.168.1.26
    port: 9093
    feignurl: http://192.168.1.26:9093/v1/dev/userprofile

buuygulama:
  birdeger: "birdeğer"