# DİKKAT!!!!! Sistem Ortam Deişkenlerine işlenen bilgiler, IDE yeniden başlatılana kadar aktif olmaz.
server:
  port: ${AUTH_PORT}

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: sales-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/DBauthmicroservice
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

myapplication:
  auth:
    ip: localhost
    port: ${AUTH_PORT}
  user:
    ip: localhost
    port: 9093
    feignurl: http://localhost:9093/v1/dev/userprofile

buuygulama:
  birdeger: ${AUTH_BIRDEGER}