server:
  port: 9093

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: userprofile-service
  data:
    mongodb:
      host: localhost
      port: 27000
      database: Java4DB
      username: JavaUser
      password: Aa123456

myapplication:
  feignclient:
    elasticsearch: http://localhost:9100/userprofile