server:
  port: 80
spring:
  application:
    name: api-gateway-microservice
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - RewritePath= /(?<segment>.*) , /v1/dev/$\{segment}
      routes:
        - id: auth-service
          uri: http://localhost:9090
          predicates:
            - Path=/auth/**
